CREATE TABLE PERFIL (
	IDPERFIL	UNIQUEIDENTIFIER	NOT NULL,
	NOME		NVARCHAR(50)		NOT NULL,
	PRIMARY KEY(IDPERFIL)
)
GO

CREATE TABLE USUARIO (
	IDUSUARIO	UNIQUEIDENTIFIER	NOT NULL,
	NOME		NVARCHAR(150)		NOT NULL,
	EMAIL		NVARCHAR(100)		NOT NULL UNIQUE,
	SENHA		NVARCHAR(40)		NOT NULL,
	DATACADASTRO	DATETIME		NOT NULL,
	IDPERFIL	UNIQUEIDENTIFIER	NOT NULL,
	PRIMARY KEY(IDUSUARIO),
	FOREIGN KEY(IDPERFIL) REFERENCES PERFIL(IDPERFIL)
)
GO


